-- This script populates the database with dummy data

USE Project1;


INSERT INTO ROLES VALUES (0);
INSERT INTO ROLES VALUES (1);

-- INSERT INTO AC_JUNCTION (ACCOUNT_ID, CUSTOMER_ID)
INSERT INTO JUNCTION (TRAIN_ID, USER_ID) VALUES (1, 1);
INSERT INTO JUNCTION (TRAIN_ID, USER_ID) VALUES (2, 2);

-- INSERT INTO TICKETS (ACCOUNT_TYPE, BALANCE)
INSERT INTO TICKETS (TICKET_ID, DESCRIPTION) VALUES (1, "My Description");
INSERT INTO TICKETS (TICKET_ID, DESCRIPTION) VALUES (2, "I'm with stupid");

-- INSERT INTO CUSTOMERS (CUSTOMER_ID, EMAIL, LAST_NAME, FIRST_NAME)
INSERT INTO USERS (USER_ID, TICKET_ID, USERNAME, PASSWORD, USER_ROLE, ROLE_ID) VALUES (1, 1, 'KMART', 'password', 'Admin', 1);
INSERT INTO USERS (USER_ID, TICKET_ID, USERNAME, PASSWORD, USER_ROLE, ROLE_ID) VALUES (2, 2, 'HAM', 'password', 'Passenger', 0);

-- INSERT INTO ACCOUNTS (ACCOUNT_TYPE, BALANCE)
INSERT INTO TRAINS (TRAIN_ID, TICKET_ID, PASSENGERS, ARRIVAL_STATION, DEPARTURE_STATION, ARRIVAL_INFO, DEPARTURE_INFO, AVAILABLE) VALUES (1, 1, 1, "LA", "GA", '2021-12-31 12:23:10', '2022-01-04 04:00:30', true);
INSERT INTO TRAINS (TRAIN_ID, TICKET_ID, PASSENGERS, ARRIVAL_STATION, DEPARTURE_STATION, ARRIVAL_INFO, DEPARTURE_INFO, AVAILABLE) VALUES (2, 2, 2, "LA", "GA", '2021-12-31 12:23:10', '2022-01-04 04:00:30', true);