-- This script does random queries

# DB Tables Reference
# CUSTOMERS (CUSTOMER_ID, LAST_NAME, FIRST_NAME, ACCOUNT_ID)
# ACCOUNTS (CUSTOMER_ID, ACCOUNT_ID, BALANCE)
# AC_JUNCTION (JUNCTION_ID, ACCOUNT_ID, CUSTOMER_ID)

USE Project0;


SELECT c.FIRST_NAME 
FROM CUSTOMERS c
WHERE c.CUSTOMER_ID = 01;

/*SELECT CUSTOMERS
FROM CUSTOMERS c
JOIN ACCOUNTS a
WHERE c.CUSTOMER_ID ON a.CUSTOMER_ID;*/
